spring:
  application:
    name: deal-api-user
  config:
    import: classpath:application-core.yml
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

server:
  port: 8080
