ALTER TABLE tb_users ADD COLUMN phone VARCHAR(20) NULL;
ALTER TABLE tb_users ADD COLUMN login_failed_count INT NOT NULL DEFAULT 0;
ALTER TABLE tb_users ADD COLUMN locked_at DATETIME NULL;
ALTER TABLE tb_users ADD COLUMN require_password_change BOOLEAN NOT NULL DEFAULT FALSE;
