spring:
  application:
    name: deal-consumer
  config:
    import: classpath:application-core.yml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: deal-order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

server:
  port: 8083
